# ==============================================================================
# 07_figures_tables.R -- render manuscript figures (.pdf) and tables (.tex)
# ==============================================================================
# Consumes saved result objects (data/results/*.rds) and tidy series, writes:
#   Figures/fig_allowance_prices.pdf         (RGGI clearing prices, VA shading)
#   Figures/scm_gap_<event>_<outcome>.pdf    (SCM gap plots)        [Phase 3]
#   Figures/eventstudy_<event>_<outcome>.pdf (DiD coefficient plots)[Phase 3]
#   Figures/placebo_<event>_<outcome>.pdf    (placebo distributions)[Phase 3]
#   Tables/tab_main_<event>.tex              (modelsummary / etable)[Phase 3]
#   Tables/tab_data_sources.tex              (from VINTAGES.csv)
# The manuscript pulls these via \includegraphics / \input. No hand-entered numbers.
#
# GUARD: this script writes into the manuscript's Figures/ and Tables/ and
# therefore refuses to run from synthetic data (RGGI_USE_SAMPLE has no effect
# here by design -- sample results never become manuscript artifacts).
# ==============================================================================
source(if (file.exists("scripts/R/00_setup.R")) "scripts/R/00_setup.R" else if (file.exists("00_setup.R")) "00_setup.R" else file.path(Sys.getenv("RGGI_ROOT"), "scripts", "R", "00_setup.R"))

save_fig <- function(plot, name, width = 6.5, height = 4) {
  ggsave(file.path(DIRS$figures, paste0(name, ".pdf")), plot,
         width = width, height = height, device = cairo_pdf)
}

assert_real <- function(dt, what) {
  if (isTRUE(dt$synthetic[1]))
    stop("[07_figures_tables] ", what, " is SYNTHETIC -- manuscript artifacts ",
         "are only rendered from real data.")
  invisible(dt)
}

# --- Figure: RGGI allowance clearing prices (all auctions, VA periods shaded) --
fig_allowance_prices <- function() {
  f <- file.path(DIRS$data_tidy, "allowance_price_auction.rds")
  if (!file.exists(f)) { message("skip fig_allowance_prices: run 01_fetch_rggi.R"); return(invisible()) }
  au <- as.data.table(readRDS(f))
  au <- au[date >= as.Date("2015-01-01")]
  shade <- data.table(
    xmin  = c(EVENTS$entry, EVENTS$reentry),
    xmax  = c(EVENTS$exit, max(max(au$date), EVENTS$reentry)),
    label = "Virginia in RGGI"
  )
  p <- ggplot(au, aes(date, clearing_price)) +
    geom_rect(data = shade, aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf),
              inherit.aes = FALSE, fill = "grey85", alpha = 0.6) +
    geom_vline(xintercept = EVENTS$reentry_signed,
               linetype = "dashed", linewidth = 0.3) +
    geom_step(linewidth = 0.5) +
    geom_point(size = 1) +
    scale_y_continuous(labels = function(x) sprintf("$%.0f", x)) +
    labs(x = NULL, y = "Clearing price ($/short ton)",
         caption = paste("Shaded: Virginia participation. Dashed line: HB 29",
                         "signing (Feb. 2026). Source: RGGI, Inc. auction results."))
  save_fig(p, "fig_allowance_prices")
  message("[07_figures_tables] wrote Figures/fig_allowance_prices.pdf")
}

# --- Table: data sources with vintages (from VINTAGES.csv) ---------------------
make_data_sources_table <- function() {
  vf <- file.path(DIRS$data_raw, "VINTAGES.csv")
  if (!file.exists(vf)) { message("skip tab_data_sources: no VINTAGES.csv yet"); return(invisible()) }
  v <- fread(vf)
  labels <- c(
    eia_861m_retail      = "Retail price, revenue, sales (EIA-861M)",
    eia923_derived_co2   = "CO$_2$ emissions, derived (EIA-923 fuel $\\times$ EPA factors)",
    rggi_auctions        = "Allowance auction results (RGGI, Inc.)",
    noaa_cpc_degree_days = "Heating/cooling degree days (NOAA CPC)",
    fred_henry_hub       = "Henry Hub natural gas spot (FRED: DHHNGSP)"
  )
  v[, label := fifelse(source %in% names(labels), labels[source], source)]
  lines <- c(
    "% Generated by scripts/R/07_figures_tables.R from data/raw/VINTAGES.csv -- do not edit.",
    "\\begin{table}[H]", "\\centering",
    "\\caption{Data sources (public), with vintages.}",
    "\\label{tab:data-sources}",
    "\\begin{threeparttable}",
    "\\begin{tabular}{@{}p{7.6cm}p{4.2cm}p{2.2cm}@{}}", "\\toprule",
    "Series & Coverage & Accessed \\\\", "\\midrule",
    v[, sprintf("%s & %s & %s \\\\", label, coverage, accessed)],
    "\\midrule",
    "Wholesale LMPs (PJM Data Miner 2.0) & \\multicolumn{2}{l}{\\emph{pending (API key required)}} \\\\",
    "\\bottomrule", "\\end{tabular}",
    "\\begin{tablenotes}\\footnotesize",
    "\\item \\textit{Notes:} All series are public and re-downloadable; the pipeline",
    "records each access in \\texttt{data/raw/VINTAGES.csv}. The emissions series is",
    "derived from EIA-923 fuel consumption and EPA emission factors pending CAMPD access.",
    "\\end{tablenotes}",
    "\\end{threeparttable}", "\\end{table}")
  writeLines(lines, file.path(DIRS$tables, "tab_data_sources.tex"))
  message("[07_figures_tables] wrote Tables/tab_data_sources.tex")
}

# --- Phase 3+: estimation figures/tables (once 03-05 run on real data) --------
# scm gap / placebo plots and etable outputs consume data/results/*.rds objects
# with NO "_SAMPLE" suffix; sample-tagged objects are never rendered here.

if (sys.nframe() == 0) {
  pf <- file.path(DIRS$data_tidy, "panel_state_month.rds")
  if (file.exists(pf)) assert_real(readRDS(pf), "panel_state_month.rds")
  fig_allowance_prices()
  make_data_sources_table()
}
